### ISSUE TITLE
Ice Creeper causing crash

### ISSUE THREAD

**Issue by Muffintiem** [Luligabi1/ElementalCreepersRefabricated#15]
In Release Candidate 1 I got a crash. The crash report mentioned "class me.luligabi.elementalcreepers.common.entity.creeper.IceCreeperEntity tried to access private method 'float net.minecraft.class_1959.method_21740"

Ice Creepers were spawning normally with no crashes in 1.18 Pre-release 5.

**Comment by Muffintiem** [comment]
Still exists in Release Candidate 3.

**Comment by Muffintiem** [comment]
Still exists in 1.18.

**Comment by Luligabi1** [comment]
Hi, this should be fixed for a while now. Sorry for the inconvenience!
