### ISSUE TITLE
no puedo jugar Minecraft 1.16.5 ForgeOptiFine con el mod ElementalCreepers | I can't play Minecraft 1.16.5 Forge OptiFine with ElementalCreepers Mod

### ISSUE THREAD

**Issue by Lenis-Felipe** [Luligabi1/ElementalCreepersRefabricated#17]
hola, tengo minecraft Tlauncher y juego la versión 1.16.5 de minecraft ForgeOptifine que es la última versión que puedo jugar en mi ordenador ya que si intento jugar en las versiones 1.17 en adelante se cuelga, descargué el mod elementalcreepers para la versión 1.16.5 que tengo pero aparece esto
![image](https://user-images.githubusercontent.com/93104242/179850758-28bcd6c7-a59f-44c3-acc4-306c08e1803b.png)
y si intento iniciar la Fabric 1.16.5 como se muestra en la imagen de arriba sale esto
![image](https://user-images.githubusercontent.com/93104242/179850899-ae640bb2-7e27-4850-9e64-d5b077683e81.png)
hace años tenia la 1.12.2 con el mod para esa pero decidí actualizar, y cuando descargo el mod para la versión que tengo aparece este error ¿alguna solución para poder jugar MC FOf 1.16.5 con el mod? gracias

**Comment by Luligabi1** [comment]
Hola,

Para jugar, debes estar en Fabric, siempre usando [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api) correspondiente a tu versión de Minecraft. Para 1.16.5, usa [esta versión de Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3510322) y [esta versión de Elemental Creepers: Refabricated](https://www.curseforge.com/minecraft/mc-mods/elemental-creepers-refabricated/files/3277909).

**Comment by Lenis-Felipe** [comment]
> Hola,
> 
> Para jugar, debes estar en Fabric, siempre usando [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api) correspondiente a tu versión de Minecraft. Para 1.16.5, usa [esta versión de Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3510322) y [esta versión de Elemental Creepers: Refabricated](https://www.curseforge.com/minecraft/mc-mods/elemental-creepers-refabricated/files/3277909).

¿no existe el mod elementalcreepers para la version 1.16.5 optifine?

**Comment by Luligabi1** [comment]
> > Hola,
> > Para jugar, debes estar en Fabric, siempre usando [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api) correspondiente a tu versión de Minecraft. Para 1.16.5, usa [esta versión de Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3510322) y [esta versión de Elemental Creepers: Refabricated](https://www.curseforge.com/minecraft/mc-mods/elemental-creepers-refabricated/files/3277909).
> 
> ¿no existe el mod elementalcreepers para la version 1.16.5 optifine?

Fabric solo.

**Comment by Lenis-Felipe** [comment]
¿no pueden crear para la forge?, me aparece ese error de incompatible set si intento iniciar Minecraft 1.16.5 Fabric
