### ISSUE TITLE
Crash when trying to run as a server

### ISSUE THREAD

**Issue by Mr-Syntax** [Luligabi1/ElementalCreepersRefabricated#20]
[latest.log](https://github.com/Luligabi1/ElementalCreepersRefabricated/files/10716764/latest.log)

**Comment by Mr-Syntax** [comment]
there was a version on curseforge that got removed which didnt have this problem, but i cant downgrade to that version anymore

**Comment by Luligabi1** [comment]
I'll look into it tomorrow, thanks for reporting!

**Comment by Mr-Syntax** [comment]
np, thanks for the mod

**Comment by Luligabi1** [comment]
Reuploaded `1.4.3+1.19`, works on dev env

**Comment by Mr-Syntax** [comment]
thanks bro <3
