### ISSUE TITLE
Creepers spawn in dark air

### ISSUE THREAD

**Issue by Slainlight** [Luligabi1/ElementalCreepersRefabricated#6]
I was on a super flat world, and i set a 50x50 area of blocks in the air and suddenly creepers were spawning underneath!

**Comment by Luligabi1** [comment]
Yeah, that's currently an issue with Fabric's `BiomeModifications` API, that handles natural spawning. At the moment I can't offer an solution as the same happened when implementing natural spawning with Mixins, as frustrating as this is. When/if a solution comes around, I'll be sure to update the mod ASAP, but for the time being this will be open.

**Comment by Luligabi1** [comment]
Hi, I looked deeper on the issue and seem to have found an solution using `SpawnRestrictionAccessor#callRegister`. This change is live on the beta branch, but an actual release with this fixed will come out this weeked plus some new features. Thank you for the report!

**Comment by Slainlight** [comment]
thank you for fixing it :) good work, love your mod
